{"uuid": "6b620d38-6bca-41ff-a36d-d98c0699a63c", "children": ["b5501553-d155-4d13-bcb7-209dfeb940fd"], "befores": [{"name": "web_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=112.0.5615.50)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EDDCE3+50899]\n\t(No symbol) [0x00E6E111]\n\t(No symbol) [0x00D75588]\n\t(No symbol) [0x00D5D333]\n\t(No symbol) [0x00DBF4DB]\n\t(No symbol) [0x00DCDB33]\n\t(No symbol) [0x00DBB6F6]\n\t(No symbol) [0x00D97708]\n\t(No symbol) [0x00D9886D]\n\tGetHandleVerifier [0x01143EAE+2566302]\n\tGetHandleVerifier [0x011792B1+2784417]\n\tGetHandleVerifier [0x0117327C+2759788]\n\tGetHandleVerifier [0x00F75740+672048]\n\t(No symbol) [0x00E78872]\n\t(No symbol) [0x00E741C8]\n\t(No symbol) [0x00E742AB]\n\t(No symbol) [0x00E671B7]\n\tBaseThreadInitThunk [0x76207D69+25]\n\tRtlInitializeExceptionChain [0x77A7B74B+107]\n\tRtlClearBits [0x77A7B6CF+191]\n\n", "trace": "  File \"D:\\project\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\project\\project_01\\test_dir\\conftest.py\", line 60, in web_login\n    Page.search_input_password = password\n  File \"D:\\project\\venv\\lib\\site-packages\\poium\\selenium.py\", line 156, in __set__\n    self.send_keys(value)\n  File \"D:\\project\\venv\\lib\\site-packages\\poium\\selenium.py\", line 244, in send_keys\n    elem.send_keys(value)\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 230, in send_keys\n    self._execute(\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 403, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681109370085, "stop": 1681109371677}], "start": 1681109370085, "stop": 1681109371826}